import { useEffect, useState, useCallback } from "react";
import { Link, useNavigate } from "react-router-dom";
import { API_URL } from "../../config/api";
import { DS } from "../../styles/ds";
import { ClipboardList, Bookmark, Sprout, Plus, Eye, Trash2, Printer, Trophy, Bot, AlertTriangle, MapPin, Maximize2 } from "lucide-react";

const authHeaders = () => ({
  Authorization: `Bearer ${localStorage.getItem("agroconnect_token")}`,
  "Content-Type": "application/json",
});

const fmt = n => `₹${Number(n || 0).toLocaleString("en-IN")}`;

function ScoreBadge({ score }) {
  const color = score >= 75 ? "#4ade80" : score >= 50 ? "#fbbf24" : "#f87171";
  const bg    = score >= 75 ? "rgba(34,197,94,0.12)" : score >= 50 ? "rgba(251,191,36,0.12)" : "rgba(239,68,68,0.12)";
  return (
    <div style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "4px 12px", borderRadius: 20, background: bg, border: `1px solid ${color}30` }}>
      <div style={{ width: 6, height: 6, borderRadius: "50%", background: color }} />
      <span style={{ color, fontWeight: 800, fontSize: 13 }}>{score}/100</span>
    </div>
  );
}

// Reusable PDF print function (same as SmartFarmPlanner)
function printPlan(plan) {
  const top = plan.recommendations?.[0];
  const rec = (plan.recommendations || []).slice(0, 5);
  const html = `
<!DOCTYPE html><html><head><title>${plan.title}</title>
<style>
  body { font-family:Arial,sans-serif; max-width:800px; margin:0 auto; padding:24px; color:#111; }
  h1 { color:#16a34a; border-bottom:2px solid #16a34a; padding-bottom:8px; }
  h2 { color:#065f46; margin-top:24px; }
  table { width:100%; border-collapse:collapse; margin:12px 0; }
  th { background:#dcfce7; color:#14532d; padding:8px 12px; text-align:left; }
  td { border-bottom:1px solid #e5e7eb; padding:8px 12px; }
  .badge { display:inline-block; padding:3px 10px; border-radius:4px; font-size:12px; font-weight:700; }
  .green { background:#dcfce7; color:#14532d; }
  .yellow { background:#fef9c3; color:#713f12; }
  .red { background:#fee2e2; color:#7f1d1d; }
</style></head><body>
<h1>${plan.title}</h1>
<p><strong>Location:</strong> ${plan.location} &nbsp;|&nbsp; <strong>Farm Area:</strong> ${plan.farmArea}</p>
<p><strong>Generated:</strong> ${new Date(plan.createdAt).toLocaleDateString("en-IN", { day:"numeric", month:"long", year:"numeric" })}</p>
<h2>Top Crop Recommendation</h2>
<p><strong>${top?.crop || "—"}</strong> — Score: ${top?.totalScore || "—"}/100</p>
<h2>All Recommendations</h2>
<table>
  <thead><tr><th>#</th><th>Crop</th><th>Score</th><th>Season</th><th>Soil</th></tr></thead>
  <tbody>${rec.map((r, i) => `<tr><td>${i + 1}</td><td>${r.crop}</td><td><span class="badge ${r.totalScore >= 75 ? "green" : r.totalScore >= 50 ? "yellow" : "red"}">${r.totalScore}/100</span></td><td>${r.season || "—"}</td><td>${r.soil || "—"}</td></tr>`).join("")}</tbody>
</table>
${plan.aiExplanation ? `<h2>AI Explanation</h2><p style="line-height:1.8">${plan.aiExplanation.replace(/\n/g, "<br/>")}</p>` : ""}
<p style="margin-top:32px;color:#6b7280;font-size:12px;">Generated by AgroConnect 360 — Smart Farm Planner</p>
</body></html>`;

  const w = window.open("", "_blank");
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => { w.print(); }, 400);
}

export default function SavedFarmPlans() {
  const navigate = useNavigate();
  const [plans, setPlans]     = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState("");
  const [deleting, setDeleting] = useState(null);
  const [selected, setSelected] = useState(null);
  const [loadingFull, setLoadingFull] = useState(false);

  const load = useCallback(() => {
    setLoading(true);
    fetch(`${API_URL}/api/farmer/smart-farm-plans`, { headers: authHeaders() })
      .then(r => r.json())
      .then(d => { if (d.success) setPlans(d.plans); else setError(d.message || "Unable to load plans"); })
      .catch(e => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => { load(); }, [load]);

  const handleDelete = async (id) => {
    if (!window.confirm("Delete this farm plan?")) return;
    setDeleting(id);
    try {
      const r = await fetch(`${API_URL}/api/farmer/smart-farm-plans/${id}`, { method: "DELETE", headers: authHeaders() });
      const d = await r.json();
      if (d.success) { setPlans(p => p.filter(x => x._id !== id)); if (selected?._id === id) setSelected(null); }
      else setError(d.message || "Delete failed");
    } catch { setError("Delete failed"); }
    finally { setDeleting(null); }
  };

  const handleViewFull = async (plan) => {
    setLoadingFull(true);
    try {
      const r = await fetch(`${API_URL}/api/farmer/smart-farm-plans/${plan._id}`, { headers: authHeaders() });
      const d = await r.json();
      if (d.success) setSelected(d.plan);
      else setError("Could not load full plan");
    } catch { setError("Load failed"); }
    finally { setLoadingFull(false); }
  };

  return (
    <>
      <style>{DS + `
        .sp-card { background:var(--surface); border:1px solid var(--border); border-radius:16px; padding:20px; transition:border-color .2s,transform .2s; }
        .sp-card:hover { border-color:rgba(34,197,94,0.25); transform:translateY(-2px); }
        .sp-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(300px,1fr)); gap:16px; }
        .sp-crop { font-family:'Space Grotesk',sans-serif; font-size:18px; font-weight:800; color:#0f172a; margin-bottom:6px; }
        .sp-meta { font-size:12px; color:var(--text2); margin-bottom:14px; line-height:1.8; }
        .sp-actions { display:flex; gap:8px; flex-wrap:wrap; }
        .sp-detail-wrap { background:var(--surface); border:1px solid var(--border); border-radius:16px; padding:24px; margin-top:24px; }
        .sp-section { margin-bottom:20px; }
        .sp-section-title { font-size:12px; font-weight:700; color:var(--text2); text-transform:uppercase; letter-spacing:.06em; margin-bottom:10px; }
        .sp-rec-row { display:flex; align-items:center; gap:12px; padding:10px 0; border-bottom:1px solid rgba(255,255,255,0.04); }
        .sp-rank { font-size:20px; width:28px; flex-shrink:0; }
        .sp-rec-crop { font-weight:700; color:#0f172a; font-size:14px; }
        .sp-rec-meta { font-size:11px; color:var(--text2); margin-top:2px; }
      `}</style>

      <div className="pg-head">
        <div>
          <div className="eyebrow">Smart Farm Planner</div>
          <h1 className="pg-title" style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <Bookmark size={24} color="#16a34a" /> Saved Farm Plans
          </h1>
          <p className="pg-sub">Your previously generated and saved Smart Farm Plans.</p>
        </div>
        <Link to="/farmer/smart-farm-planner" className="btn-green" style={{ display: "inline-flex", alignItems: "center", gap: 6 }}>
          <Plus size={14} /> New Plan
        </Link>
      </div>

      {error && <div className="alert-error" style={{ display: "flex", alignItems: "center", gap: 8 }}><AlertTriangle size={16} /> {error}</div>}

      {loading ? (
        <div className="loading-wrap"><div className="spinner" /><span>Loading saved plans…</span></div>
      ) : plans.length === 0 ? (
        <div className="empty-state">
          <div className="empty-emoji"><ClipboardList size={40} strokeWidth={1.5} color="#bbf7d0" /></div>
          <div className="empty-title">No saved plans yet</div>
          <div className="empty-sub">Generate a Smart Farm Plan and click "Save Farm Plan" to keep it for later.</div>
          <Link to="/farmer/smart-farm-planner" className="btn-green" style={{ marginTop: 16, display: "inline-flex", alignItems: "center", gap: 6 }}>
            <Plus size={14} /> Generate a Plan
          </Link>
        </div>
      ) : (
        <>
          <div className="sp-grid">
            {plans.map(plan => (
              <div key={plan._id} className="sp-card">
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 10 }}>
                  <ScoreBadge score={plan.topScore || 0} />
                  <span style={{ fontSize: 11, color: "var(--text2)" }}>
                    {new Date(plan.createdAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}
                  </span>
                </div>
                <div className="sp-crop" style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <Sprout size={16} color="#16a34a" /> {plan.topCrop || "—"}
                </div>
                <div className="sp-meta" style={{ display: "flex", flexDirection: "column", gap: 4 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 4 }}><MapPin size={12} /> {plan.location || "—"}</div>
                  <div style={{ display: "flex", alignItems: "center", gap: 4 }}><Maximize2 size={12} /> {plan.farmArea || "—"}</div>
                </div>
                <div style={{ fontSize: 12, color: "#94a3b8", marginBottom: 14, fontWeight: 500 }}>
                  {plan.title}
                </div>
                <div className="sp-actions">
                  <button
                    className="btn-ghost"
                    style={{ fontSize: 12, padding: "7px 14px", color: "#0369a1", borderColor: "rgba(56,189,248,0.2)", display: "inline-flex", alignItems: "center", gap: 6 }}
                    onClick={() => handleViewFull(plan)}
                    disabled={loadingFull}
                  >
                    {loadingFull ? "…" : <><Eye size={13} /> View Full Plan</>}
                  </button>
                  <button
                    className="btn-ghost"
                    style={{ fontSize: 12, padding: "7px 14px", color: "#dc2626", borderColor: "rgba(239,68,68,0.2)", display: "inline-flex", alignItems: "center", justifyContent: "center" }}
                    onClick={() => handleDelete(plan._id)}
                    disabled={deleting === plan._id}
                  >
                    {deleting === plan._id ? "…" : <Trash2 size={13} />}
                  </button>
                </div>
              </div>
            ))}
          </div>

          {/* Full plan detail panel */}
          {selected && (
            <div className="sp-detail-wrap">
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }}>
                <div>
                  <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 20, fontWeight: 800, color: "#0f172a" }}>{selected.title}</div>
                  <div style={{ fontSize: 13, color: "var(--text2)", marginTop: 4 }}>
                    {selected.location} · {selected.farmArea} · {new Date(selected.createdAt).toLocaleDateString("en-IN")}
                  </div>
                </div>
                <div style={{ display: "flex", gap: 10 }}>
                  <button className="btn-green" style={{ fontSize: 12, display: "inline-flex", alignItems: "center", gap: 6 }} onClick={() => printPlan(selected)}>
                    <Printer size={13} /> Download PDF
                  </button>
                  <button className="btn-ghost" style={{ fontSize: 12 }} onClick={() => setSelected(null)}>✕ Close</button>
                </div>
              </div>

              {/* Recommendations */}
              <div className="sp-section">
                <div className="sp-section-title" style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <Trophy size={16} color="#16a34a" /> Crop Recommendations
                </div>
                {(selected.recommendations || []).slice(0, 5).map((rec, i) => {
                  return (
                    <div key={i} className="sp-rec-row">
                      <span className="sp-rank" style={{ fontWeight: 800, color: i === 0 ? "#16a34a" : i === 1 ? "#0369a1" : "#64748b" }}>#{i + 1}</span>
                      <div style={{ flex: 1 }}>
                        <div className="sp-rec-crop">{rec.crop}</div>
                        <div className="sp-rec-meta">
                          Season: {rec.season || "—"} · Soil: {rec.soil || "—"}
                          {rec.marketPrice > 0 ? ` · Market: ${fmt(rec.marketPrice)}/q` : ""}
                        </div>
                      </div>
                      <ScoreBadge score={rec.totalScore || 0} />
                    </div>
                  );
                })}
              </div>

              {/* AI Explanation */}
              {selected.aiExplanation && (
                <div className="sp-section" style={{ padding: "16px 20px", background: "#faf5ff", border: "1px solid rgba(167,139,250,0.15)", borderRadius: 14 }}>
                  <div className="sp-section-title" style={{ display: "flex", alignItems: "center", gap: 6 }}>
                    <Bot size={16} color="#7c3aed" /> AI Explanation
                  </div>
                  <p style={{ fontSize: 13, color: "var(--text)", lineHeight: 1.8, whiteSpace: "pre-wrap", margin: 0 }}>{selected.aiExplanation}</p>
                </div>
              )}

              {/* Farm Details */}
              <div className="sp-section" style={{ marginTop: 16 }}>
                <div className="sp-section-title" style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <ClipboardList size={16} color="#16a34a" /> Farm Input at Time of Plan
                </div>
                <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))", gap: 10 }}>
                  {Object.entries(selected.farmDetails || {}).filter(([k]) => !["location"].includes(k)).map(([k, v]) => (
                    v != null && v !== "" ? (
                      <div key={k} style={{ background: "var(--surface2)", border: "1px solid var(--border)", borderRadius: 10, padding: "10px 14px" }}>
                        <div style={{ fontSize: 10, color: "var(--text2)", fontWeight: 700, textTransform: "uppercase", marginBottom: 4 }}>{k}</div>
                        <div style={{ fontSize: 13, fontWeight: 700, color: "#0f172a" }}>{String(v)}</div>
                      </div>
                    ) : null
                  ))}
                </div>
              </div>
            </div>
          )}
        </>
      )}
    </>
  );
}
